#!/bin/bash

## this script is only run if actual change to domain/path is detected, if you're here either $domain or $path changed
## new location is available via $domain and $path (or $new_domain and $new_path variables if you want to be explicit)
## old values are available via, you guessed it, $old_domain and $old_path

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# STOP SERVICE
#=================================================
ynh_script_progression "Stopping $app's service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE SERVER URL
#=================================================
if [[ "$new_path" == "/" ]]; then
    server_url="https://${new_domain}"
else
    server_url="https://${new_domain}${new_path}"
fi

ynh_app_setting_set --key=server_url --value="$server_url"

ynh_config_add --template="twenty.env" --destination="$install_dir/.env"
chmod 600 "$install_dir/.env"

#=================================================
# START SERVICE
#=================================================
ynh_script_progression "Starting $app's service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
