#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

tag="1.14.0"
app_secret=$(ynh_string_random --length=64)
pg_database_user="$app"
pg_database_name="$app"
pg_database_password=$(ynh_string_random --length=32)

if [[ "$path" == "/" ]]; then
    server_url="https://${domain}"
else
    server_url="https://${domain}${path}"
fi

ynh_app_setting_set --key=tag --value="$tag"
ynh_app_setting_set --key=app_secret --value="$app_secret"
ynh_app_setting_set --key=pg_database_user --value="$pg_database_user"
ynh_app_setting_set --key=pg_database_name --value="$pg_database_name"
ynh_app_setting_set --key=pg_database_password --value="$pg_database_password"
ynh_app_setting_set --key=server_url --value="$server_url"

#=================================================
# SETUP FILES
#=================================================
ynh_script_progression "Setting up configuration files..."

mkdir -p "$install_dir" "$data_dir/db" "$data_dir/server-local-data"

ynh_config_add --template="docker-compose.yml" --destination="$install_dir/docker-compose.yml"
ynh_config_add --template="twenty.env" --destination="$install_dir/.env"

chmod 600 "$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="TwentyCRM service"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
