#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# UPDATE SETTINGS
#=================================================
if [[ "$path" == "/" ]]; then
    server_url="https://${domain}"
else
    server_url="https://${domain}${path}"
fi

ynh_app_setting_set --key=server_url --value="$server_url"

#=================================================
# UPDATE CONFIGURATION FILES
#=================================================
ynh_script_progression "Updating $app's configuration files..."

mkdir -p "$install_dir" "$data_dir/db" "$data_dir/server-local-data"

ynh_config_add --template="docker-compose.yml" --destination="$install_dir/docker-compose.yml"
ynh_config_add --template="twenty.env" --destination="$install_dir/.env"

chmod 600 "$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="TwentyCRM service"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
